version: 2
project_name: testcli

builds:
  - id: testcli
    main: ./cmd/testcli/main.go
    env:
      - CGO_ENABLED=0
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w -X github.com/btschwartz12/testcli/pkg/version.Version={{ .Version }} -X github.com/btschwartz12/testcli/pkg/version.Commit={{ .Commit }} -X github.com/btschwartz12/testcli/pkg/version.Date={{ .Date }}
    binary: testy

archives:
  - id: default
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - completions/*
      - docs/*

homebrew_casks:
  - name: testcli
    ids:
      - default
    binary: testy
    repository:
      owner: btschwartz12
      name: homebrew-tap
    url:
      template: "https://github.com/btschwartz12/testcli/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
      verified: "github.com/btschwartz12/testcli/"
    completions:
      bash: completions/testy.bash
      zsh: completions/_testy

    commit_msg_template: "Brew cask update for {{ .ProjectName }} version {{ .Tag }}"
    description: "Test CLI"
    homepage: "https://github.com/btschwartz12/testcli"

    # https://goreleaser.com/customization/homebrew_casks#signing-and-notarizing
    hooks:
      post:
          install: |
            if OS.mac?
              system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/testy"]
            end
    
    caveats: |
      NOTE: the install executable is 'testy', not 'testcli'. For more info, visit https://github.com/btschwartz12/testcli

checksum:
  name_template: "checksums.txt"

release:
  draft: false
  prerelease: auto

changelog:
  use: github
