version: 2
project_name: testy

builds:
  - id: testy
    main: ./cmd/testcli/main.go
    env:
      - CGO_ENABLED=0
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w -X github.com/btschwartz12/testcli/pkg/version.Version={{ .Version }} -X github.com/btschwartz12/testcli/pkg/version.Commit={{ .Commit }} -X github.com/btschwartz12/testcli/pkg/version.Date={{ .Date }}
    binary: testy

archives:
  - id: default
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md

homebrew_casks:
  - name: testcli
    ids:
      - default
    binary: testy
    repository:
      owner: btschwartz12
      name: homebrew-tap
    url:
      template: "https://github.com/btschwartz12/testcli/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
      verified: "github.com/btschwartz12/testcli/"
    completions:
      bash: completions/testy.bash
      zsh: completions/_testy
    skip_upload: true
    caveats: |
      The binary for this cask has been renamed to `testy` from `testcli`.

      See the README for more information: https://github.com/btschwartz12/testcli


checksum:
  name_template: "checksums.txt"

release:
  draft: false
  prerelease: auto

changelog:
  use: github
