version: 2
project_name: testcli

builds:
  - id: testcli
    main: ./cmd/testcli/main.go
    env:
      - CGO_ENABLED=0
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w -X github.com/btschwartz12/testcli/pkg/version.Version={{ .Version }} -X github.com/btschwartz12/testcli/pkg/version.Commit={{ .Commit }} -X github.com/btschwartz12/testcli/pkg/version.Date={{ .Date }}
    binary: testcli

archives:
  - id: default
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md

homebrew_casks:
  - name: testcli
    ids:
      - default        # match your archive id
    binary: testcli
    tap:
      owner: btschwartz12
      name: homebrew-testcli
    url:
      template: "https://github.com/{{ .ProjectGitOwner }}/{{ .ProjectGitName }}/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
      verified: "github.com/{{ .ProjectGitOwner }}/{{ .ProjectGitName }}/"

checksum:
  name_template: "checksums.txt"

release:
  draft: false
  prerelease: auto

changelog:
  use: github
